# NAIVE BAYES

# Aprendizagem bayesiana - Naive Bayes
Usado principalmente para tratamento de textos

Exemplo:
- Filtros de spam
- Mineração de emoções
- Separação de documentos

In [1]:
import pandas as pd
pd.DataFrame.iteritems = pd.DataFrame.items #Isso é pra corrigir um erro no 'iteritems' que dá na geração do gráfico na hora que usa o "px.scatter_matrix"
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px
from sklearn.preprocessing import StandardScaler #Para o LabelEncoder
from sklearn.preprocessing import LabelEncoder #Para o LabelEncoder
from sklearn.preprocessing import OneHotEncoder #Para o OneHotEncoder
from sklearn.compose import ColumnTransformer #Para o OneHotEncoder
from sklearn.preprocessing import StandardScaler #Para o OneHotEncoder
from sklearn.model_selection import train_test_split
import pickle #Pra salvar os dados já tratados
from sklearn.naive_bayes import GaussianNB


In [2]:
#Lendo a base de dados
base_risco_credito = pd.read_csv("Bases de dados/risco_credito.csv")
base_risco_credito

historia divida garantias     renda     risco
0           ruim   alta   nenhuma      0_15      alto
1   desconhecida   alta   nenhuma     15_35      alto
2   desconhecida  baixa   nenhuma     15_35  moderado
3   desconhecida  baixa   nenhuma  acima_35      alto
4   desconhecida  baixa   nenhuma  acima_35     baixo
5   desconhecida  baixa  adequada  acima_35     baixo
6           ruim  baixa   nenhuma      0_15      alto
7           ruim  baixa  adequada  acima_35  moderado
8            boa  baixa   nenhuma  acima_35     baixo
9            boa   alta  adequada  acima_35     baixo
10           boa   alta   nenhuma      0_15      alto
11           boa   alta   nenhuma     15_35  moderado
12           boa   alta   nenhuma  acima_35     baixo
13          ruim   alta   nenhuma     15_35      alto

In [3]:
#Criando a variável X - Dos valores
X_risco_credito = base_risco_credito.iloc[:, 0:4].values
X_risco_credito

array([['ruim', 'alta', 'nenhuma', '0_15'],
       ['desconhecida', 'alta', 'nenhuma', '15_35'],
       ['desconhecida', 'baixa', 'nenhuma', '15_35'],
       ['desconhecida', 'baixa', 'nenhuma', 'acima_35'],
       ['desconhecida', 'baixa', 'nenhuma', 'acima_35'],
       ['desconhecida', 'baixa', 'adequada', 'acima_35'],
       ['ruim', 'baixa', 'nenhuma', '0_15'],
       ['ruim', 'baixa', 'adequada', 'acima_35'],
       ['boa', 'baixa', 'nenhuma', 'acima_35'],
       ['boa', 'alta', 'adequada', 'acima_35'],
       ['boa', 'alta', 'nenhuma', '0_15'],
       ['boa', 'alta', 'nenhuma', '15_35'],
       ['boa', 'alta', 'nenhuma', 'acima_35'],
       ['ruim', 'alta', 'nenhuma', '15_35']], dtype=object)

In [4]:
#Criando a variárvel y - Das classes
y_risco_credito = base_risco_credito.iloc[:,4].values
y_risco_credito

array(['alto', 'alto', 'moderado', 'alto', 'baixo', 'baixo', 'alto',
       'moderado', 'baixo', 'baixo', 'alto', 'moderado', 'baixo', 'alto'],
      dtype=object)

In [5]:
#Criando um label encoder para cada coluna
label_encoder_historia = LabelEncoder()
label_encoder_divida = LabelEncoder()
label_encoder_garantia = LabelEncoder()
label_encoder_renda = LabelEncoder()

In [6]:
#Codificando os dados em números através do fit_transform, do labelencoder
X_risco_credito[:, 0] = label_encoder_historia.fit_transform(X_risco_credito[:,0])
X_risco_credito[:, 1] = label_encoder_divida.fit_transform(X_risco_credito[:,1])
X_risco_credito[:, 2] = label_encoder_garantia.fit_transform(X_risco_credito[:,2])
X_risco_credito[:, 3] = label_encoder_renda.fit_transform(X_risco_credito[:,3])

In [7]:
#Observando a nova tabela
X_risco_credito

array([[2, 0, 1, 0],
       [1, 0, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 2],
       [1, 1, 1, 2],
       [1, 1, 0, 2],
       [2, 1, 1, 0],
       [2, 1, 0, 2],
       [0, 1, 1, 2],
       [0, 0, 0, 2],
       [0, 0, 1, 0],
       [0, 0, 1, 1],
       [0, 0, 1, 2],
       [2, 0, 1, 1]], dtype=object)

In [8]:
#Salvando os dados pré-processados
with open('risco_credito.pkl', 'wb') as f:
    pickle.dump([X_risco_credito, y_risco_credito], f)

In [9]:
#Aqui importa o GaussianNB para trabalhar alguns dados da tabela gerada
#Vamo usar o 'from sklearn.nayve_bayes import GaussianNB' só que vou importar lá encima!
naive_risco_credito = GaussianNB()
naive_risco_credito.fit(X_risco_credito, y_risco_credito)

GaussianNB()

In [10]:
#Agora, vamo usar a variável "naive_risco_credito" pra calcular os dois seguintes casos:
#História boa (0), dívida alta (0), garantia nenhuma (1), renda > 35 (2)
#História ruim (2), divida alta (0), garantias adequada (0), renda < 35 (0)
#Lembrando que os números entre parênteses são tirados da comparação entre a tabela de variáveis categóricas e a tabela de variáveis numéricas

previsao = naive_risco_credito.predict([[0,0,1,2], [2,0,0,0]])
previsao

array(['baixo', 'moderado'], dtype='<U8')

In [11]:
#Observando as classes existentes
naive_risco_credito.classes_

array(['alto', 'baixo', 'moderado'], dtype='<U8')

In [13]:
#Contando a quantidade total de cada classe
naive_risco_credito.class_count_

array([6., 5., 3.])

In [15]:
#Observando a quantidade de risco em porcentagem
naive_risco_credito.class_prior_ * 100

array([42.85714286, 35.71428571, 21.42857143])